url_root: http://www.neubloc.pl/

navigation_kariera:
- text: Kariera
  url: ../kariera/
- text: C/C++ Software Development Engineer
  url: ../kariera/c-software-development-engineers.html
  - text: C#/.NET Software Development Engineer
  url: ../kariera/net-software-development-engineers.html

navigation_kontakt:
- text: Kontakt
  url: ../kontakt/

navigation_o:
- text: O Neubloc
  url: ../o-neubloc/
- text: Historia
  url: ../o-neubloc/historia.html
- text: Management
  url: ../o-neubloc/management.html

navigation_portfolio:
- text: Portfolio
  url: ../portfolio/
- text: Case Studies
  url: ../portfolio/case-studies.html