default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: neublocsite_development
  username: neublocsite
  password: password2
  host: localhost
test: &TEST
  adapter: postgresql
  encoding: unicode
  database: neublocsite_test
  pool: 5
  username: neublocsite
  port: 5432
  password: password2

production:
  adapter: postgresql
  encoding: utf8
  database: d24btth76hov9q
  pool: 5
  username: rtblemzlunkaci
  password: e4ae92ff2ae2d89c79185b59dcdaff283b71a222b9b1a4c424d22227a1e90d25